// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS1MGmnQpfP7nDFr3bGl2ARbEQXHKhjC0',
    appId: '1:1059046013178:web:4b7142a00ecc085bcef143',
    messagingSenderId: '1059046013178',
    projectId: 'waterqualityapp-ef1f6',
    authDomain: 'waterqualityapp-ef1f6.firebaseapp.com',
    storageBucket: 'waterqualityapp-ef1f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzChqJZccqRvzipChe8pqsgG6WP38g9to',
    appId: '1:1059046013178:android:2821c66b9b930a83cef143',
    messagingSenderId: '1059046013178',
    projectId: 'waterqualityapp-ef1f6',
    storageBucket: 'waterqualityapp-ef1f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTrEOSJyXF4neTlfLQJguMKhI9EUqWvZ0',
    appId: '1:1059046013178:ios:544678dc2cfa44b5cef143',
    messagingSenderId: '1059046013178',
    projectId: 'waterqualityapp-ef1f6',
    storageBucket: 'waterqualityapp-ef1f6.appspot.com',
    iosClientId: '1059046013178-527aerigv0fs66eeukkgdm4b938ake68.apps.googleusercontent.com',
    iosBundleId: 'waterQualitytestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTrEOSJyXF4neTlfLQJguMKhI9EUqWvZ0',
    appId: '1:1059046013178:ios:fe7d30ba0f1342cccef143',
    messagingSenderId: '1059046013178',
    projectId: 'waterqualityapp-ef1f6',
    storageBucket: 'waterqualityapp-ef1f6.appspot.com',
    iosClientId: '1059046013178-j0md5mj2eet31s95b80dr3rv1831a825.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterQualityApp',
  );
}
