// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWED9G7OquZcAlxAjMEG_R8-VVgv0kYOw',
    appId: '1:172517360734:web:b65c426bb23b36585720cf',
    messagingSenderId: '172517360734',
    projectId: 'fir-flutter-codelab-5824f',
    authDomain: 'fir-flutter-codelab-5824f.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5824f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADoZenk5L3BygfkJKmgoaSG-rDH4fJi0g',
    appId: '1:172517360734:android:e0350744631916445720cf',
    messagingSenderId: '172517360734',
    projectId: 'fir-flutter-codelab-5824f',
    storageBucket: 'fir-flutter-codelab-5824f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzSllYEhrNZGBMFZiw0-XKTLh3HwzbOAY',
    appId: '1:172517360734:ios:a3a970294fd6175b5720cf',
    messagingSenderId: '172517360734',
    projectId: 'fir-flutter-codelab-5824f',
    storageBucket: 'fir-flutter-codelab-5824f.appspot.com',
    iosClientId: '172517360734-8laiprbk5cdb406tr98mihse1n23fg4o.apps.googleusercontent.com',
    iosBundleId: 'waterQualityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzSllYEhrNZGBMFZiw0-XKTLh3HwzbOAY',
    appId: '1:172517360734:ios:d206eb533ce4baf55720cf',
    messagingSenderId: '172517360734',
    projectId: 'fir-flutter-codelab-5824f',
    storageBucket: 'fir-flutter-codelab-5824f.appspot.com',
    iosClientId: '172517360734-l2oq3jnkae8ecnl692loafn1n26d6216.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterQualityApp',
  );
}
