// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4DAsgfHv9zqTU5_3Pz54j561PKcxWVw',
    appId: '1:523682544880:web:f1e64ffd4e0b6d36841635',
    messagingSenderId: '523682544880',
    projectId: 'fir-flutter-codelab-88915',
    authDomain: 'fir-flutter-codelab-88915.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-88915.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYpDHvM_zeYWxncW0BpnUiHHsXj4fw_XI',
    appId: '1:523682544880:android:8b3915a7bdb5e960841635',
    messagingSenderId: '523682544880',
    projectId: 'fir-flutter-codelab-88915',
    storageBucket: 'fir-flutter-codelab-88915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMVH0b12OLdtI7B_fFVW-G1yt3G4H8Wck',
    appId: '1:523682544880:ios:b3d696a1030ed68c841635',
    messagingSenderId: '523682544880',
    projectId: 'fir-flutter-codelab-88915',
    storageBucket: 'fir-flutter-codelab-88915.appspot.com',
    iosClientId: '523682544880-vqdef5p6e5a0mh80dnjn7g4m2iq1646k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMVH0b12OLdtI7B_fFVW-G1yt3G4H8Wck',
    appId: '1:523682544880:ios:b3d696a1030ed68c841635',
    messagingSenderId: '523682544880',
    projectId: 'fir-flutter-codelab-88915',
    storageBucket: 'fir-flutter-codelab-88915.appspot.com',
    iosClientId: '523682544880-vqdef5p6e5a0mh80dnjn7g4m2iq1646k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
